//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WebotsSpot
{
    [Serializable]
    public class LegsMsg : Message
    {
        public const string k_RosMessageName = "webots_spot_msgs/Legs";
        public override string RosMessageName => k_RosMessageName;

        //  Front left leg
        //  Front right leg
        //  Rear left leg
        //  Rear right leg
        public double[] leg;

        public LegsMsg()
        {
            this.leg = new double[12];
        }

        public LegsMsg(double[] leg)
        {
            this.leg = leg;
        }

        public static LegsMsg Deserialize(MessageDeserializer deserializer) => new LegsMsg(deserializer);

        private LegsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.leg, sizeof(double), 12);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.leg);
        }

        public override string ToString()
        {
            return "LegsMsg: " +
            "\nleg: " + System.String.Join(", ", leg.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
