//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WebotsSpot
{
    [Serializable]
    public class PeakAndDetectObjectFeedback : Message
    {
        public const string k_RosMessageName = "webots_spot_msgs/PeakAndDetectObject";
        public override string RosMessageName => k_RosMessageName;

        public string status;

        public PeakAndDetectObjectFeedback()
        {
            this.status = "";
        }

        public PeakAndDetectObjectFeedback(string status)
        {
            this.status = status;
        }

        public static PeakAndDetectObjectFeedback Deserialize(MessageDeserializer deserializer) => new PeakAndDetectObjectFeedback(deserializer);

        private PeakAndDetectObjectFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "PeakAndDetectObjectFeedback: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
