//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WebotsSpot
{
    [Serializable]
    public class PeakAndDetectObjectGoal : Message
    {
        public const string k_RosMessageName = "webots_spot_msgs/PeakAndDetectObject";
        public override string RosMessageName => k_RosMessageName;

        public string image;

        public PeakAndDetectObjectGoal()
        {
            this.image = "";
        }

        public PeakAndDetectObjectGoal(string image)
        {
            this.image = image;
        }

        public static PeakAndDetectObjectGoal Deserialize(MessageDeserializer deserializer) => new PeakAndDetectObjectGoal(deserializer);

        private PeakAndDetectObjectGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.image);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "PeakAndDetectObjectGoal: " +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
