//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WebotsSpot
{
    [Serializable]
    public class PeakAndDetectObjectResult : Message
    {
        public const string k_RosMessageName = "webots_spot_msgs/PeakAndDetectObject";
        public override string RosMessageName => k_RosMessageName;

        public string @object;

        public PeakAndDetectObjectResult()
        {
            this.@object = "";
        }

        public PeakAndDetectObjectResult(string @object)
        {
            this.@object = @object;
        }

        public static PeakAndDetectObjectResult Deserialize(MessageDeserializer deserializer) => new PeakAndDetectObjectResult(deserializer);

        private PeakAndDetectObjectResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@object);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@object);
        }

        public override string ToString()
        {
            return "PeakAndDetectObjectResult: " +
            "\n@object: " + @object.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
