//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WebotsSpot
{
    [Serializable]
    public class StackGoal : Message
    {
        public const string k_RosMessageName = "webots_spot_msgs/Stack";
        public override string RosMessageName => k_RosMessageName;

        public string block;
        public string location;

        public StackGoal()
        {
            this.block = "";
            this.location = "";
        }

        public StackGoal(string block, string location)
        {
            this.block = block;
            this.location = location;
        }

        public static StackGoal Deserialize(MessageDeserializer deserializer) => new StackGoal(deserializer);

        private StackGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.block);
            deserializer.Read(out this.location);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.block);
            serializer.Write(this.location);
        }

        public override string ToString()
        {
            return "StackGoal: " +
            "\nblock: " + block.ToString() +
            "\nlocation: " + location.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
