//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.WebotsSpot
{
    [Serializable]
    public class StackResult : Message
    {
        public const string k_RosMessageName = "webots_spot_msgs/Stack";
        public override string RosMessageName => k_RosMessageName;

        public bool stacked;

        public StackResult()
        {
            this.stacked = false;
        }

        public StackResult(bool stacked)
        {
            this.stacked = stacked;
        }

        public static StackResult Deserialize(MessageDeserializer deserializer) => new StackResult(deserializer);

        private StackResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stacked);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stacked);
        }

        public override string ToString()
        {
            return "StackResult: " +
            "\nstacked: " + stacked.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
